######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 14 12:00:30 2016
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += enums.h psocif.h
SOURCES += psocif.cpp TestPSOC.cpp
