######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 14 12:11:07 2016
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += TestQString.h
SOURCES += TestQString.cpp
