######################################################################
# Automatically generated by qmake (2.01a) Sat Oct 15 21:07:55 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . ../../qtest
INCLUDEPATH += .

# Input
